// <auto-generated />
namespace FreedomTransportation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedaforeignkeytoprovidercustomeranddriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedaforeignkeytoprovidercustomeranddriver));
        
        string IMigrationMetadata.Id
        {
            get { return "201811201458448_added a foreign key to provider,customer and driver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
