// <auto-generated />
namespace FreedomTransportation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedanewmodelforfuturebooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedanewmodelforfuturebooking));
        
        string IMigrationMetadata.Id
        {
            get { return "201811261941183_added a new model for future booking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
