// <auto-generated />
namespace FreedomTransportation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class walletidandridesarenownullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(walletidandridesarenownullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811191854433_wallet id and rides are now nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
